// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrizeScenario.Data;

namespace PrizeScenario.Migrations
{
    [DbContext(typeof(DrawContext))]
    partial class DrawContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PrizeScenario.Models.Participant", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 2,
                            FirstName = "Jane",
                            LastName = "Doe",
                            PostCode = "T35711"
                        },
                        new
                        {
                            UserId = 3,
                            FirstName = "Joe",
                            LastName = "Smith",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 4,
                            FirstName = "Jane",
                            LastName = "Smith",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 5,
                            FirstName = "Sam",
                            LastName = "Fisher",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 6,
                            FirstName = "Wonder",
                            LastName = "Woman",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 7,
                            FirstName = "Patrick",
                            LastName = "Star",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 8,
                            FirstName = "Patrick",
                            LastName = "Stewart",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 9,
                            FirstName = "Spongebob",
                            LastName = "Squarepants",
                            PostCode = "T35710"
                        },
                        new
                        {
                            UserId = 10,
                            FirstName = "Pete",
                            LastName = "Armstrong",
                            PostCode = "T35710"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
